"""Test migration. Table can be deleted with next migration

Revision ID: d11cba3114ff
Revises: 
Create Date: 2021-12-05 00:48:31.412472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11cba3114ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('breed', sa.Enum('BRITISH', 'MAINE_COON', 'SIAM', name='catbreed'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['kitties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kitties')
    # ### end Alembic commands ###
